[book]
title = "한국전쟁의 숨겨진 역사"
author = ["I.F. Stone"]
language = "ko"
multilingual = false
src = "src"

[output.html]
# 사이트 스타일 커스터마이징 (선택)
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true
additional-css = ["css/custom.css"]